package dev.specialize.processor.registry;

import dev.specialize.processor.model.ExplicitSpecialization;
import dev.specialize.processor.model.GeneratedSpecialization;
import dev.specialize.processor.model.ReferenceTarget;
import dev.specialize.processor.model.SourceTemplate;
import dev.specialize.processor.model.Specialization;
import dev.specialize.processor.model.TargetTuple;
import dev.specialize.processor.model.Template;
import dev.specialize.processor.resolve.Annotations;
import dev.specialize.processor.resolve.TreeUtil;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.stream.Stream;
import javax.lang.model.util.Elements;

/** The specializations known so far, by name and by (template, targets). */
final class SpecializationIndex {
    private record Key(String template, TargetTuple tuple) {
        static Key of(Template template, TargetTuple tuple) {
            return new Key(template.qualified(), tuple);
        }
    }

    private final Elements elements;
    private final AnnotationReader reader;
    private final Function<String, Optional<Template>> templates;
    private final Predicate<String> typeExists;
    private final Map<String, Optional<Specialization>> byName = new HashMap<>();
    private final Map<Key, ExplicitSpecialization> explicitByKey = new HashMap<>();
    private final Map<Key, Optional<Specialization>> resolvedByKey = new HashMap<>();

    SpecializationIndex(Elements elements, AnnotationReader reader, Function<String, Optional<Template>> templates, Predicate<String> typeExists) {
        this.elements = elements;
        this.reader = reader;
        this.templates = templates;
        this.typeExists = typeExists;
    }

    /** Whether a name will denote a specialization this run generates. */
    boolean willBeGenerated(String qualified) {
        return byName.getOrDefault(qualified, Optional.empty()).isPresent();
    }

    void record(Specialization spec) {
        byName.put(spec.qualified(), Optional.of(spec));
        resolvedByKey.put(Key.of(spec.template(), spec.type()), Optional.of(spec));
    }

    void recordExplicit(Specialization spec) {
        record(spec);
        if (spec instanceof ExplicitSpecialization explicit) {
            explicitByKey.put(Key.of(spec.template(), spec.type()), explicit);
        }
    }

    /** Autoscan grew the template: the earlier "no such specialization" answer no longer holds. */
    void forgetResolution(Template template, TargetTuple tuple) {
        resolvedByKey.remove(Key.of(template, tuple));
    }

    /** Explicit first, then the conventionally named class: generated by this run, or found on the class path. */
    Optional<Specialization> specializationFor(Template template, TargetTuple tuple) {
        return resolvedByKey.computeIfAbsent(Key.of(template, tuple), key -> {
            Optional<Specialization> found = Optional.<Specialization>ofNullable(explicitByKey.get(key))
                    .or(() -> lookupByConvention(template, tuple));
            found.ifPresent(spec -> byName.putIfAbsent(spec.qualified(), found));
            return found;
        });
    }

    /** In the template's package, or (for a type another module asked for) next to that type. */
    private Optional<Specialization> lookupByConvention(Template template, TargetTuple tuple) {
        String conventional = template.conventionalName(tuple);
        boolean willExist = (template instanceof SourceTemplate source && source.compiledHere()) || typeExists.test(conventional);
        if (template.tuples().contains(tuple) && willExist) {
            return Optional.of(new GeneratedSpecialization(conventional, template, tuple));
        }
        return Stream.concat(Stream.of(conventional), nextToTarget(tuple, conventional).stream())
                .map(this::specByName).flatMap(Optional::stream)
                .filter(spec -> spec.template().qualified().equals(template.qualified()) && spec.type().equals(tuple))
                .findFirst();
    }

    private static Optional<String> nextToTarget(TargetTuple tuple, String conventional) {
        return tuple.isSingle() && tuple.single() instanceof ReferenceTarget reference && !TreeUtil.packageOf(reference.key()).isEmpty()
                ? Optional.of(TreeUtil.packageOf(reference.key()) + "." + TreeUtil.simpleName(conventional))
                : Optional.empty();
    }

    /** Any specialization by class name: registered, generated by this run, or annotated on the class path. */
    Optional<Specialization> specByName(String qualified) {
        return byName.computeIfAbsent(qualified, q -> Optional.ofNullable(elements.getTypeElement(q))
                .filter(element -> AnnotationValues.mirror(element, Annotations.SPECIALIZED).isPresent())
                .flatMap(element -> reader.specialization(element, Optional.empty(), templates)));
    }

    List<ExplicitSpecialization> explicitSpecializationsOf(Template template) {
        return explicitByKey.values().stream()
                .filter(spec -> spec.template().qualified().equals(template.qualified()))
                .toList();
    }
}
