package dev.specialize.processor.specialize;

import dev.specialize.processor.model.GeneratedSpecialization;
import dev.specialize.processor.model.SourceTemplate;
import dev.specialize.processor.model.Template.TypeParameter;
import dev.specialize.processor.resolve.TreeUtil;

import com.sun.tools.javac.code.Flags;
import com.sun.tools.javac.tree.JCTree;
import com.sun.tools.javac.tree.JCTree.JCClassDecl;
import com.sun.tools.javac.tree.JCTree.JCMethodDecl;
import com.sun.tools.javac.tree.JCTree.JCVariableDecl;
import com.sun.tools.javac.tree.Pretty;
import java.io.IOException;
import java.io.StringWriter;
import java.util.stream.Collectors;

/** Renders a specialized class as a source file; records need their own header because {@code Pretty} prints them as classes. */
public final class SourceRenderer {
    private SourceRenderer() {
    }

    public static String render(SourceTemplate template, GeneratedSpecialization spec, JCClassDecl tree) throws IOException {
        StringWriter out = new StringWriter();
        String destination = TreeUtil.packageOf(spec.qualified());
        if (!destination.isEmpty()) {
            out.append("package ").append(destination).append(";\n\n");
        }
        template.unit().getImports().forEach(imp -> out.append(imp.toString()));
        if (!destination.equals(template.pkg())) {
            out.append("import ").append(template.pkg()).append(".*;\n");
        }
        String parameters = template.parameters().stream().map(TypeParameter::name).collect(Collectors.joining(", "));
        out.append("\n/** Generated by @Specialize from ").append(template.simple()).append('<').append(parameters)
                .append("> for ").append(spec.type().key()).append(". Do not edit. */\n");
        if ((tree.mods.flags & Flags.RECORD) != 0) {
            renderRecord(tree, out);
        } else {
            new Pretty(out, true).printStat(tree);
        }
        return out.append('\n').toString();
    }

    private static boolean isRecordComponent(JCTree def) {
        return def instanceof JCVariableDecl v && (v.mods.flags & Flags.RECORD) != 0;
    }

    private static void renderRecord(JCClassDecl record, StringWriter out) throws IOException {
        Pretty pretty = new Pretty(out, true);
        record.mods.annotations.forEach(annotation -> out.append(annotation.toString()).append('\n'));
        String components = record.defs.stream().filter(SourceRenderer::isRecordComponent).map(JCVariableDecl.class::cast)
                .map(v -> v.vartype + " " + v.name)
                .collect(Collectors.joining(", "));
        String typeParameters = record.typarams.isEmpty() ? ""
                : record.typarams.stream().map(Object::toString).collect(Collectors.joining(", ", "<", ">"));
        out.append(Flags.toString(record.mods.flags & Flags.AccessFlags)).append(" record ").append(record.name.toString())
                .append(typeParameters).append('(').append(components).append(')');
        if (record.implementing.nonEmpty()) {
            out.append(" implements ").append(record.implementing.stream().map(Object::toString).collect(Collectors.joining(", ")));
        }
        out.append(" {\n");
        for (JCTree def : record.defs) {
            switch (def) {
                case JCVariableDecl v when isRecordComponent(v) -> { }
                case JCMethodDecl m when (m.mods.flags & Flags.COMPACT_RECORD_CONSTRUCTOR) != 0 -> {
                    out.append("    ").append(Flags.toString(m.mods.flags & Flags.AccessFlags)).append(' ')
                            .append(record.name.toString()).append(' ');
                    pretty.printStat(m.body);
                    out.append('\n');
                }
                default -> {
                    pretty.printStat(def);
                    out.append('\n');
                }
            }
        }
        out.append("}");
    }
}
